name: Deploy JSDocs Documentation

on:
    push:
        branches:
            - main
            - Add-JSDocs-Building

jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        name: Build and Deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Build Docs
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir: ./src
                  output_dir: ./out
                  recurse: true
                  template: tidy-jsdoc
            - name: Upload to Cloudflare
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy ./out --project-name=docs-dev-journal --commit-dirty=true
