name: E2E Testing

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v4
            - name: Upload Worker Version
              id: deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy src/ --project-name=dev-journal --commit-dirty=true
            - name: print deployment-url
              env:
                  DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
              run: echo DEPLOYMENT_URL=${DEPLOYMENT_URL} >> .env
            - name: Run Tests
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run e2etest

