name: ESLint

on: [push]

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - run: npm ci
            - name: Run ESLint
              run: npx eslint --config .config/eslint.config.js src/
