name: Node Unit Test

on: [push]

jobs:
    unittests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: populate .env
              run: printf '%s\n'
                  echo EXPORT_FOR_TESTS = TRUE >> .env
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run unittest
